[tool.ruff]
select = ["UP"]
ignore = ["UP015"]
target-version = "py38"

[project]
name = "FletPageManager"
version = "0.1.0"
description = "Flet Page Manager"
readme = "README.md"
authors = [
    {name = "Zhan Rongrui", email = "2742392377@qq.com"},
]
dependencies = [
    "flet>=0.10.1",
    "loguru>=0.7.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
